### ISSUE TITLE
Errors on Classic due to 9.x template

### ISSUE THREAD

**Issue by Road-block** [sfmict/HidingBar#1]
#### Environment
* Addon version: v1.13.20
* WoW version: 1.13.5 (Classic)

#### Actual Behaviour

```
			["message"] = "Couldn't find inherited node: BackdropTemplate",
			["time"] = "2020/10/17 05:35:11",
			["session"] = 7222,
			["counter"] = 27,
```

#### Screenshots

Most addons that do compatibility with 9.x and previous versions create frames in Lua which lets them conditionally check for existence of the BackdropTemplateMixin in the global namespace before inheriting from BackdropTemplate.

I'm not sure there's a way to do the same in xml off the top of my head which causes the addon to error repeatedly.

**Comment by sfmict** [comment]
Thx for report, in game version 1.13.6 no errors, let's fix it now.

**Comment by sfmict** [comment]
Fixed, check.
