### ISSUE TITLE
Adding Addon to Ignore List destroyed HidingBar

### ISSUE THREAD

**Issue by Kjelden** [sfmict/HidingBar#11]
#### Environment
* Addon version: v1.14.10
* WoW version: 2.5.3 (41812)

#### How can we reproduce it.  Please be specific!

- Every Addon was added into Bar 1

- Made a second bar(Bar 2)

- Went to Ignore List

- Added the button 'Atlasloot'

- UI reloaded

#### What was expected to happen?!
No idea.

#### What happened instead?!

- Lost All "Bars" in HidingBars, All buttons back on minimap

- Opened HidingBars menu/config

- No longer have Profile 1 or Bars 1 and  2

- Can not add any new profiles

- Can not add any buttons automatically or manually

#### Screenshots
![hidingbar click profile](https://user-images.githubusercontent.com/98801633/151926609-941a5fdd-8a02-45a7-9f31-00494ac1e7b0.PNG)

**Comment by sfmict** [comment]
You're using the classic version addon for the tbc version wow.

**Comment by Kjelden** [comment]
Yeah, I was messing with older versions of the Addon looking for a fix. Forgot to change it back.
Same issue.
![hidingbar 2](https://user-images.githubusercontent.com/98801633/151929245-86b8beaa-ffc8-4b24-abf4-71bb269bda78.PNG)

**Comment by sfmict** [comment]
Can you install [BugGrabber](https://www.curseforge.com/wow/addons/bug-grabber) and [BugSack](https://www.curseforge.com/wow/addons/bugsack) then write what they give?

**Comment by Kjelden** [comment]
1x HidingBar\HidingBar-v2.5.15.lua:949: attempt to call method 'GetName' (a nil value)
[string "@HidingBar\HidingBar-v2.5.15.lua"]:949: in function <HidingBar\HidingBar.lua:948>
[string "=(tail call)"]: ?
[string "@HidingBar\HidingBar-v2.5.15.lua"]:453: in function `init'
[string "@HidingBar\HidingBar-v2.5.15.lua"]:710: in function `setProfile'
[string "@HidingBar\HidingBar-v2.5.15.lua"]:329: in function <HidingBar\HidingBar.lua:329>

Locals:
self = HidingBarAddon {
 charDB = <table> {
 }
 UI_SCALE_CHANGED = <function> defined @HidingBar\HidingBar.lua:383
 setBtnParent = <function> defined @HidingBar\HidingBar.lua:804
 minimapButtons = <table> {
 }
 currentProfile = <table> {
 }
 setHooks = <function> defined @HidingBar\HidingBar.lua:1050
 pConfig = <table> {
 }
 init = <function> defined @HidingBar\HidingBar.lua:400
 setMBtnSettings = <function> defined @HidingBar\HidingBar.lua:793
 setBtnSettings = <function> defined @HidingBar\HidingBar.lua:785
 off = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:153
 ignoreCheck = <function> defined @HidingBar\HidingBar.lua:390
 addButton = <function> defined @HidingBar\HidingBar.lua:860
 checkProfile = <function> defined @HidingBar\HidingBar.lua:334
 sort = <function> defined @HidingBar\HidingBar.lua:1093
 cb = <table> {
 }
 db = <table> {
 }
 setClipButtons = <function> defined @HidingBar\HidingBar.lua:1115
 UnregisterAllCallbacks = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:174
 0 = <userdata>
 ldbi_add = <function> defined @HidingBar\HidingBar.lua:927
 ldb_add = <function> defined @HidingBar\HidingBar.lua:810
 mixedButtons = <table> {
 }
 setProfile = <function> defined @HidingBar\HidingBar.lua:686
 on = <function> defined @AtlasLootClassic\Libs\CallbackHandler-1.0\CallbackHandler-1.0.lua:90
 profiles = <table> {
 }
 addCustomGrabButton = <function> defined @HidingBar\HidingBar.lua:914
 grabMinimapAddonsButtons = <function> defined @HidingBar\HidingBar.lua:938
 addMButton = <function> defined @HidingBar\HidingBar.lua:948
 updateBars = <function> defined @HidingBar\HidingBar.lua:741
 createdButtons = <table> {
 }
 bars = <table> {
 }
 ldb_attrChange = <function> defined @HidingBar\HidingBar.lua:817
 barByName = <table> {
 }
}
button = <table> {
 IsSpellKnownForLoad = <function> defined @WeakAuras\Prototypes.lua:1062
 unitLoadFrame = <unnamed> {
 }
 IsRetail = <function> defined @WeakAuras\Init.lua:47
 GetRuneCooldown = <function> defined @WeakAuras\GenericTrigger.lua:1972
 GetUnitFrame = <function> defined @WeakAuras\Libs\LibGetFrame-1.0\LibGetFrame-1.0.lua:251
 CheckRange = <function> defined @WeakAuras\Prototypes.lua:35
 CheckTalentByIndex = <function> defined @WeakAuras\Prototypes.lua:907
 ShowOverlayGlow = <function> defined @WeakAuras\Libs\LibCustomGlow-1.0\LibCustomGlow-1.0.lua:601
 RegisterItemCountWatch = <function> defined @WeakAuras\GenericTrigger.lua:3449
 CheckForItemBonusId = <function> defined @WeakAuras\GenericTrigger.lua:4043
 UnitCastingInfo = <function> defined =[C]:-1
 GetRegion = <function> defined @WeakAuras\WeakAuras.lua:2824
 InstanceTypeRaw = <function> defined @WeakAuras\WeakAuras.lua:1387
 RealTimeProfilingWindow = <unnamed> {
 }
 GetSpellCharges = <function> defined @WeakAuras\GenericTrigger.lua:2010
 SafeToNumber = <function> defined @WeakAuras\WeakAuras.lua:5013
 GetAllDBMTimers = <function> defined @WeakAuras\GenericTrigger.lua:2921
 ToggleProfile = <function> defined @WeakAuras\Profiling.lua:377
 IsAuraActive = <function> defined @WeakAuras\WeakAuras.lua:4370
 regionOptions = <table> {
 }
 SetRegion = <function> defined @WeakAuras\WeakAuras.lua:2721
 EnsureString = <function> defined @WeakAuras\WeakAuras.lua:3551
 CheckMPlusAffixIds = <function> defined @WeakAuras\Prototypes.lua:993
 WatchForCastLatency = <function> define

**Comment by Kjelden** [comment]
10x HidingBar\HidingBar-v2.5.15.lua:39: attempt to call method 'enter' (a nil value)
[string "@HidingBar\HidingBar-v2.5.15.lua"]:39: in function <HidingBar\HidingBar.lua:35>
[string "@HidingBar\HidingBar-v2.5.15.lua"]:965: in function <HidingBar\HidingBar.lua:965>
[string "=[C]"]: ?

Locals:
btn = LibDBIcon10_BugSack {
 0 = <userdata>
 fadeOut = <unnamed> {
 }
 SetFixedFrameStrata = <function> defined @HidingBar\HidingBar.lua:34
 isMouseDown = false
 SetHeight = <function> defined @HidingBar\HidingBar.lua:34
 SetAlpha = <function> defined @HidingBar\HidingBar.lua:34
 SetScript = <function> defined @HidingBar\HidingBar.lua:1043
 CreateAnimationGroup = <function> defined @HidingBar\HidingBar.lua:1037
 db = <table> {
 }
 HookScript = <function> defined @HidingBar\HidingBar.lua:34
 icon = <unnamed> {
 }
 Hide = <function> defined @HidingBar\HidingBar.lua:34
 ClearAllPoints = <function> defined @HidingBar\HidingBar.lua:34
 SetScale = <function> defined @HidingBar\HidingBar.lua:34
 dataObject = <table> {
 }
 StartMoving = <function> defined @HidingBar\HidingBar.lua:34
 SetFixedFrameLevel = <function> defined @HidingBar\HidingBar.lua:34
 SetIgnoreParentScale = <function> defined @HidingBar\HidingBar.lua:34
 IsShown = <function> defined @HidingBar\HidingBar.lua:1030
 SetSize = <function> defined @HidingBar\HidingBar.lua:34
 Show = <function> defined @HidingBar\HidingBar.lua:34
 SetParent = <function> defined @HidingBar\HidingBar.lua:34
 SetWidth = <function> defined @HidingBar\HidingBar.lua:34
 SetPoint = <function> defined @HidingBar\HidingBar.lua:34
 SetShown = <function> defined @HidingBar\HidingBar.lua:34
 SetHitRectInsets = <function> defined @HidingBar\HidingBar.lua:34
 SetEnabled = <function> defined @HidingBar\HidingBar.lua:34
 Disable = <function> defined @HidingBar\HidingBar.lua:34
}
bar = Minimap {
 timer = 0
 isMouse = true
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = Minimap {
 timer = 0
 isMouse = true
 0 = <userdata>
}
(*temporary) = "attempt to call method 'enter' (a nil value)"

**Comment by sfmict** [comment]
Thx you. It seems to me, i solved your problem, you need to install [this version](https://github.com/sfmict/HidingBar/releases/tag/v2.5.16-alpha1).

**Comment by Kjelden** [comment]
Works perfectly now. I attempted to recreate what broke it last time and it's now working.

**Comment by sfmict** [comment]
Thx you for feedback :)
