### ISSUE TITLE
Feature Request: control addon minimap icon tooltips and set custom anchor

### ISSUE THREAD

**Issue by addonaddict** [sfmict/HidingBar#12]
#### Environment
* Addon version: 9.2.2
* WoW version: 9.2

#### Desired functionality
Please consider adding a feature to "hijack" addon tooltips and anchor them by user preference globally.
Anchor options would be typical like top, bottom left, left, etc. Could also use other anchor points not related to the addon button. 
The reason this is needed is because so many addons out there anchor their tooltips completely randomly with no thought involved.
In some cases as you move cursor between addons, the addon window closes as the tooltip goes in the forefront. Extremely annoying.
Below example is when using "bar like a minimap button" option, in "show to down" mode.

Example 1:
![image](https://user-images.githubusercontent.com/73442541/162600498-a3b584c4-258c-4414-8e94-8c0e29f0de6a.png)

Example 2:
![image](https://user-images.githubusercontent.com/73442541/162600514-72404347-17ca-45ef-9892-58de32c955a0.png)

Hope this is clear. Thanks.

**Comment by sfmict** [comment]
Hello. Firstly, user anchoring is possible and I'll do it. Second, some of the buttons have their own tooltip and I can't keep track of all of them, but SilverDragon uses the LibQTip-1.0 library, so I might be able to change the anchoring for it.

**Comment by addonaddict** [comment]
Thank you for the response. Tbh it was just an example, as about half of the addons you see on that screenshot have their tooltip "above" the bar, other half below or somewhere to the side. It seems completely random to me. Not sure what you can do with that... will wait for you to do your magic :D

**Comment by sfmict** [comment]
Done, check out the latest beta :)

**Comment by addonaddict** [comment]
Just tested, works like a charm! Thanks!
Only thing I noticed is it doesnt seem to do anything when in minimap button mode.
In normal mode, all tooltips are attached neatly in one spot. Wonderful.

**Comment by addonaddict** [comment]
Most addons are like this:
![image](https://user-images.githubusercontent.com/73442541/163013685-f25f1e05-ff42-44e9-949f-b0736fc06b60.png)

Allthethings and Oilvl addons are like this:
![image](https://user-images.githubusercontent.com/73442541/163013779-d58b0c72-dde5-4ab1-9265-69104b1433be.png)


Perhaps this is screen size issue and tooltips not fitting above? Maybe...

**Comment by addonaddict** [comment]
Forget it, it was indeed the UI scaling. Made things smaller and it worked perfectly. Thanks again!!!
![image](https://user-images.githubusercontent.com/73442541/163013968-a1526a0e-caa0-4b79-af3d-9d57879ee0ce.png)

**Comment by sfmict** [comment]
Tooltip is displayed at the bottom if it doesn't fit on top. Closed thx u for feedback.
