### ISSUE TITLE
HidingBar and ItemRack integration bug

### ISSUE THREAD

**Issue by tunder** [sfmict/HidingBar#13]
#### Environment
* Addon version: 2.5.24
* WoW version: 2.5.4

#### Steps to reproduce
Install addon and ItemRack Classic (3.69 bcc version)  (https://www.curseforge.com/wow/addons/itemrack-classic)
Make 2 sets in ItemRack Classic

#### Expected Behaviour
Being able to click ItemRack Classic icon then choose one of the sets from the dropdown menu that appears

#### Actual Behaviour
Dropdown menu appears but items are not clickable (on click the hiding bar is getting hidden also)

**Comment by sfmict** [comment]
Hello, I already came across this addon, the author doesn't want to fix this problem, so I can add the option "Hide when clicking on an free space". If the option is disabled, this will allow you to press the button before the panel hides.

or you can change `ItemRack.lua` 930 line
```lua
	ItemRackMenuFrame:SetParent(relativeTo)
```
to
```lua
	-- ItemRackMenuFrame:SetParent(relativeTo)
```

**Comment by tunder** [comment]
hi,
thanks for the reply. i guess the option you are referring to would be a good fix. you already have an option for how much the panel to be visible. i guess it will not hurt to keep it visible until the timer ends.

thank you for your work. i love it.

**Comment by sfmict** [comment]
The option added, check it out :)

**Comment by tunder** [comment]
> The option added, check it out :)

works perfectly. thank you.
