### ISSUE TITLE
Separate zips for vanilla/classic/bcc

### ISSUE THREAD

**Issue by austen0** [sfmict/HidingBar#14]
#### Environment
* Addon version: n/a 
* WoW version: n/a 

#### Desired functionality
Including separate zips for each version in the github releases will make it easier to download/update the mod without Overwolf/Curseforge.

**Comment by sfmict** [comment]
The code for retail and classic was originally different, so they have different branches and their own releases. I see no reason to do a general release. You can download all versions in releases.

**Comment by austen0** [comment]
I think having the separate releases makes it more complex for managers trying to download directly from github to fetch the appropriate version. If releases always have
`HidingBar-v9.2.5.zip`
`HidingBar-v1.14.23-classic.zip`
`HidingBar-v2.5.26-bcc.zip`
then to automate fetching, all that has to be done is to grab the files from the `latest` release and the rest of the necessary info can be simply extracted from the filenames.

**Comment by austen0** [comment]
Just for context, I'm suggesting this for compatibility with [WowUp](https://wowup.io/) at the moment, but I think this is broadly applicable which is why I haven't framed it specifically as a request for WowUp integration.

**Comment by sfmict** [comment]
I see no reason to adapt to a service that will earn money from me without giving anything in return.

**Comment by austen0** [comment]
The app is free and they don't run ads on the website, so the "service" is not making money afaik. The developer has a Patreon accepting _donations_ which are earned from their own hard work building an entire app. I'd hoped since you've licensed your addon under the GPLv3 (which explicitly allows others to "earn money from you" btw) and already release directly on github that you'd be more open to making it accessible outside of the Curse API.

**Comment by sfmict** [comment]
My addon is available on github, wago.io, course. Adapting to this service will make development less convenient for me, and I will also have no statistics, no feedback, plus a decrease in payments from the course and wago. Again, I see no reason to adapt to this service.

**Comment by austen0** [comment]
Enjoy your ad revenue, bud.
