### ISSUE TITLE
Login Error

### ISSUE THREAD

**Issue by evilgodly** [sfmict/HidingBar#15]
#### Environment
* Addon version: Hiding Bar v10.0.0.beta4
* WoW version: Retail 9.2.7

#### Expected Behavior
Log in to toon and start gaming with out error.

#### Actual Behavior
I logged in and got this error right away with out doing anything. Went from Toon Select screen > loading screen > game screen with error popped up.

#### Debug Output
2x HidingBar\Config.lua:29: attempt to index global 'Settings' (a nil value)
[string "@HidingBar\Config.lua"]:29: in main chunk

Locals:
addon = "HidingBar"
L = <table> {
 About = "About"
 Right = "Right"
 Both direction = "Both direction"
 ADD_IGNORE_MBTN_QUESTION = "Are you sure you want to add to the ignore list %s?"
 Right top = "Right top"
 sec. = "sec."
 Ignore list = "Ignore list"
 Distance between buttons = "Distance between buttons"
 Bottom = "Bottom"
 Line Border Size = "|cff%sLine|r Border Size"
 Grab default buttons on minimap = "Grab default buttons on minimap"
 If a suitable bar exists then the button will be grabbed = "If a suitable bar exists then the button will be grabbed"
 Allways = "Always"
 Position of minimap buttons = "Position of minimap buttons"
 Timer or clicking on a free place = "Timer or clicking on a free place"
 Fade out bar = "Fade out bar"
 Number of buttons = "Number of buttons in a row / column"
 Top right = "Top right"
 BUTTON_TOOLTIP = "|cffffd200LMB|r to enable / disable buttons or drag to reposition.
|cffffd200RMB|r to open the context menu."
 Manually Grabbed Buttons = "Manually Grabbed Buttons"
 Followed = "Followed"
 Are you sure you want to delete profile %s? = "Are you sure you want to delete profile %s?"
 Intercept the position of tooltips = "Intercept the position of tooltips and change to"
 Point to button = "Point to button"
 Left bottom = "Left bottom"
 Timer = "Timer"
 Horizontal = "Horizontal"
 ADD_CUSTOM_GRAB_BTN_QUESTION = "Are you sure you want to add to the grab list %s?"
 Bar = "Bar"
 Opacity = "Opacity"
 Buttons Size = "Buttons Size"
 Vertical = "Vertical"
 Try to grab after = "Try to grab after"
 Add bar = "Add bar"
 Click = "Click"
 Hover = "Hover"
 Strata of panel = "Strata of panel"
 Lock the bar's location = "Lock the bar's location"
 Move to = "Move to"
 A profile with the same name exists. = "A profile with the same name exists."
 A bar with the same name exists. = "A bar with the same name exists."
 A new line = "A new line"
 Auto show/hide = "Auto show/hide"
 TEXTURES_HELP_TOOLTIP = "Some textures are added from other addons, so they may be missing if the addon is missing."
 Hover or Click = "Hover or Click"
 Show to left = "Show to left"
 Delay to show = "Delay to show"
 Direction of buttons = "Direction of buttons"
 Add to ignore list = "Add to ignore list"
 REMOVE_CUSTOM_GRAB_BTN_QUESTION = "Are you sure you want to remove %s from the grab list?"
 Border Offset = "Border Offset"
 Prevents button elements from going over the edges. = "Prevents button elements from going over the edges."
 Options of adding buttons = "Options of adding buttons"
 Clip button = "Clip button"
 Allow the button to control its own visibility = "Allow the button to control its own visibility."
 Profile = "Profile"
 DataBroker Buttons = "DataBroker Buttons"
 Left to right = "Left to right"
 Show to up = "Show to up"
 Show to right = "Show to right"
 Distance from button to bar = "Distance from button to bar"
 Bar like a minimap button = "Bar like a minimap button"
 Grab addon buttons on minimap = "Grab addon buttons on minimap"
 Own Minimap Button = "Own Minimap Button"
 Bar position = "Bar position"
 Source: = "Source:"
 IGNORE_DESCRIPTION = "You can specify a part of the name.

For example |cffffd200HidingBar|r will ignore:
|cffffd200HidingBar1|r
|cffffd200HidingBar2|r
|cffffd200HidingBar3|r
..."
 Top = "Top"
 Border Size = "Border Size"
 Line Border Offset = "|cff%sLine|r Border Offset"
 Hiding to up = "Hiding to up"
 Bar offset relative to the button = "Bar offset relative to the button"
 Line width = "|cff%sLine|r width"
 Line Border = "Line Border"
 Copy current = "Copy current"
 Bar attached to the side = "Bar attached to the side"
 Bottom right = "Bottom right"
 Clicking on a free place = "Clicking on a free place"
 author = "Author"
 Right bottom = "Right bottom"
 Add buttons from DataBroker = "Add buttons from DataBroker"
 Hiding to left = "Hiding to left"
 Localization Translators: = "Localization Translators:"
 Left top = "Left top"
 Manually added = "Manually added"
 Fade out line = "Fade out |cff%sline|r"
 Left = "Left"
 Show to down = "Show to down"
 Hide by = "Hide by"
 %s Configuration = "%s Conf

**Comment by sfmict** [comment]
Hello, you're using DragonFlight version in Retail

**Comment by evilgodly** [comment]
oh lol that would do it. Thanks
