### ISSUE TITLE
HidingBar wow prepatch error

### ISSUE THREAD

**Issue by Zetaprime82** [sfmict/HidingBar#16]
#### Environment
* Addon version:  v10.0.0-beta5
* WoW version: 10.0.0

#### Debug Output
1x Interface/AddOns/HidingBar/HidingBar.lua:46: attempt to call method 'enter' (a nil value)
[string "@Interface/AddOns/HidingBar/HidingBar.lua"]:46: in function <Interface/AddOns/HidingBar/HidingBar.lua:42>
[string "@Interface/AddOns/HidingBar/HidingBar.lua"]:1463: in function <Interface/AddOns/HidingBar/HidingBar.lua:1463>
[string "=[C]"]: ?

Locals:
btn = LibDBIcon10_AstralKeys {
 0 = <userdata>
 fadeOut = AnimationGroup {
 }
 SetFixedFrameStrata = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 isMouseDown = false
 SetHeight = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetAlpha = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 sexyMapFadeOut = AnimationGroup {
 }
 SetScript = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1387
 CreateAnimationGroup = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1380
 db = <table> {
 }
 SetPoint = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 icon = Texture {
 }
 Hide = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1365
 ClearAllPoints = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetScale = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 dataObject = <table> {
 }
 Show = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1360
 SetShown = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1348
 HookScript = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 IsShown = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1370
 SetFixedFrameLevel = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetIgnoreParentScale = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetParent = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetWidth = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetSize = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 StartMoving = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetHitRectInsets = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetEnabled = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 Disable = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
}
eventFrame = LibDBIcon10_AstralKeys {
 0 = <userdata>
 fadeOut = AnimationGroup {
 }
 SetFixedFrameStrata = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 isMouseDown = false
 SetHeight = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetAlpha = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 sexyMapFadeOut = AnimationGroup {
 }
 SetScript = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1387
 CreateAnimationGroup = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1380
 db = <table> {
 }
 SetPoint = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 icon = Texture {
 }
 Hide = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1365
 ClearAllPoints = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetScale = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 dataObject = <table> {
 }
 Show = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1360
 SetShown = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1348
 HookScript = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 IsShown = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:1370
 SetFixedFrameLevel = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetIgnoreParentScale = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetParent = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetWidth = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetSize = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 StartMoving = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetHitRectInsets = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 SetEnabled = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
 Disable = <function> defined @Interface/AddOns/HidingBar/HidingBar.lua:40
}
bar = Minimap {
 0 = <userdata>
 OnLeave = <function> defined @Interface/FrameXML/Minimap.lua:185
 OnMouseWheel = <function> defined @Interface/FrameXML/Minimap.lua:73
 OnLoad = <function> def

**Comment by sfmict** [comment]
Hello, sorry but i can't reproduce this error.

**Comment by sfmict** [comment]
Is it relevant?
