### ISSUE TITLE
DataBroker buttons not being included

### ISSUE THREAD

**Issue by kemayo** [sfmict/HidingBar#17]
#### Environment
* Addon version: v10.0.0
* WoW version: 10.0.0.46313

#### Expected Behaviour
All DataBroker plugins would be present in the HidingBar configuration.

#### Actual Behaviour
*Some* LDB plugins were included, but most weren't.

#### Debug Output
No errors occurred.

#### Screenshots
![image](https://user-images.githubusercontent.com/2187/198174584-015a62e7-5b96-4a9f-89de-94a5ddac023f.png)

**Comment by sfmict** [comment]
Hello, why do you think this is wrong behavior? The addon only takes objects with the "launcher" type, and rightly so. If developer doesn't want to add a button for other addons, i won't.

**Comment by kemayo** [comment]
Many `data source` broker plugins also function as a `launcher` if you click the icon, or are only intending to show a tooltip rather than any sort of label (and the spec only guarantees `OnTooltipShow` for `data source`) -- so even if it's (quite reasonably) missing the text display, it'd still be very useful to get the icon+tooltip.

**Comment by sfmict** [comment]
Yes, "data source" is used for most minimap buttons, etc., but if the author wanted to add it, he would. I'm not sure if this needs to be added.

**Comment by kemayo** [comment]
Could make sense to have it as another category in the "options of adding buttons" section, maybe? I'd understand it being a disabled-by-default setting, but I know I'd always turn it on (and then maybe situationally-disable some _actual_ label-only brokers, I'm sure).

**Comment by sfmict** [comment]
Maybe, i should see how it works.

**Comment by sfmict** [comment]
Added option, [check](https://github.com/sfmict/HidingBar/releases/tag/v10.0.4-beta1)

**Comment by kemayo** [comment]
Nice! That seems to work very well for my purposes. Thanks for adding it.
