### ISSUE TITLE
Masque 10.0.0 compatible

### ISSUE THREAD

**Issue by riggzh** [sfmict/HidingBar#19]
#### Environment
* Addon version: 3.4.4
* WoW version: 3.4.0.46248

#### Steps to reproduce
Update Masque to 10.0.0

#### Expected Behaviour
Nothing

#### Actual Behaviour
Can't load Masque skin
In Masque v10.0.0, they use "Default (Classic)" in WotLK not "Default"

#### Debug Output
In HidingBar.lua:89
local defTexture = MSQ:GetSkin("Default").Normal.Texture

**Comment by Xylotox** [comment]
![image](https://user-images.githubusercontent.com/9465199/198818405-c62148d1-e22d-44c4-a269-d1abf3d1c677.png)
fix:Available after modification

**Comment by sfmict** [comment]
Hello, the default skin is set to `Masque\Skins\Default.lua` but now masque uses atlas so I need a little modification :)

**Comment by Xylotox** [comment]
waiting for your modification.TK

**Comment by sfmict** [comment]
Oh, wotlk uses `Default (Classic)`, i looked at the retail, nvm fixed :).

**Comment by riggzh** [comment]
Yep. It's only in wotlk use Default (Classic). Maybe in retail keep use Default. Not check in retail

**Comment by sfmict** [comment]
As far as I understand it is fixed, closed.
