### ISSUE TITLE
[Request] Fill a row

### ISSUE THREAD

**Issue by Alucard2112** [sfmict/HidingBar#2]
I'm sorry if this is not the place to post suggestions or request.
As the addon is right now, some addons are placed within the first row whereas others are getting placed in the second row. I understand that there is some kind of distiction between how the addon was added (minimap buttons vs broker interface I presume).
I would like to see an option where this distinction is ignored outside of the settings page so that one can simply have on row of addons (and maybe sort them better) regardless of how they were added :)

P.S.: Great job! Love the addon to bits :)

**Comment by sfmict** [comment]
This is certainly possible, I myself thought about the implementation of such options, i will try to implement it in the future.

**Comment by sfmict** [comment]
Partially resolved. I am thinking whether to do a general sorting.

**Comment by addonaddict** [comment]
I agree with this, as I use everything in one row at top of my screen

**Comment by sfmict** [comment]
> 
> 
> I agree with this, as I use everything in one row at top of my screen

Addon allows to make all buttons in one line. Or do you want a general sorting?

**Comment by addonaddict** [comment]
From what i can see minimap icons and databroker icons are split up, so you cannot mix them up positioning wise when you have 1 bar
The way i have it at top of my screen, i cannot have 1 minimap icon on far left, and 1 on far right, its either all minimap icons on right, and databroker icons on left
Hope this is clear enough, thx

**Comment by sfmict** [comment]
Hi, pls check a beta version of the addon

**Comment by addonaddict** [comment]
Working great so far! Thank you so much for including this :)
