### ISSUE TITLE
Tooltip border still shows when no text is present on LFG Dungeon Eye Icon. (Not Queued)

### ISSUE THREAD

**Issue by ghost** [sfmict/HidingBar#20]
#### Environment
* Addon version: v10.0.6
* WoW version: 10.0.2.46702

#### Steps to reproduce
1. Add the Dungeon Finder Eye Icon to Hiding Bar
2. Hover over the Dungeon Finder Eye Icon on the hiding bar when not queued for a dungeon.

#### Expected Behaviour
1. Ideally, the empty tooltip would not show when there is not a dungeon queued. 
2. Alternatively, just hide the eye completely if a queue is not in progress, but even just a solution to above tooltip would be an improvement as well.

#### Actual Behaviour
1. When not queued for a dungeon, the empty tooltip when hovering over the icon still persists. Resulting in a undesirable line texture.

#### Debug Output
Not an error, but more of a potential styling oversight.

#### Screenshots
![image](https://user-images.githubusercontent.com/10183471/202866905-bca519de-3e36-40d6-8f37-6fb270b64677.png)

**Comment by sfmict** [comment]
Hello, you grabbed this button manually, so you need to set the button to "Auto show/hide" option. But it's better to enable "Grab default buttons" option.

**Comment by ghost** [comment]
Thanks! That worked. Sorry for the post, I didn't see that as an option. Appreciate the troubleshooting and feel free to close this one out then. Sorry!

Edit: In case anyone else is an idiot like me and sees this before posting - There is a right click function on icons in the /hidingbar options. The right click context menu is where you can set the auto show/hide option. Cheers.
