### ISSUE TITLE
Icons appear twice

### ISSUE THREAD

**Issue by SpareSimian** [sfmict/HidingBar#21]
* Addon version: 3.4.13
* WoW version: retail (10.1.5)

All my minimap buttons are displayed twice. I reloaded apps with only HidingBar and SavedInstances loaded and still get double buttons. There are two of each addon's button, one smaller one with a gold circle outline and a larger one. For some reason, the "small" one for Enchantrix is much larger than the large icons and spreads beyond its border to overlay the adjacent icons. 

![HidingBarDoubleButtons](https://github.com/sfmict/HidingBar/assets/1709928/c466363c-d3ea-41f6-a10a-e27c58475303)

**Comment by sfmict** [comment]
Hello, this isn't a bug, HidingBar is grabbing buttons from the minimap and DataBroker, so mb some addons can be duplicated (can be disabled in the settings).
And you're using a wotlk version of the addon for retail, I recommend changing it.

**Comment by SpareSimian** [comment]
Aha. I'd Just grabbed the release from GitHub not realizing it was for WotLK as it had a later version number from my initial test. I just installed the one from wago.io and will test later.

**Comment by SpareSimian** [comment]
The smaller icons with rings appear to come from the minimap, while the larger ones that fill the frame and are easier to see for my aging eyes come from DataBroker. If I deselect the minimap icons, then those are left cluttering the minimap. It would be nice to have an option to remove them from the minimap but not add them to the HB menu. (I still haven't figured out how to attach the HB menu to the minimap and to make it square-ish instead of a single strip of icons. Even better would be to put it in the new "compartment" above and to the right of the minimap.)

**Comment by sfmict** [comment]
You can disable any button, change button size, set number of buttons per row/column, etc. in the settings.
Also can install the Masque addon, which changes the appearance of the buttons.

**Comment by SpareSimian** [comment]
Thanks, I think I found all the relevant settings. Where do the gold rings on the minimap buttons come from? Are those removable? I don't see a setting for that. Or is there a setting to remove buttons from the minimap but not add them to the menu, so I can use the Databroker ones, instead? (I guess I can request both, and then manually remove the minimap ones.)

**Comment by sfmict** [comment]
You can disable any button, use the Masque addon to change the style.

**Comment by sfmict** [comment]
As far I understand the problem is solved, so it's closed.

**Comment by SpareSimian** [comment]
Thanks and sorry for the hassle. For those who run into a similar problem, Masque indeed addresses the icon circles. I didn't have to do anything but install it and the circles disappeared and the icons got bigger.
