### ISSUE TITLE
HidingBar can no longer hide its own button

### ISSUE THREAD

**Issue by durandal42** [sfmict/HidingBar#22]
#### Environment
* Addon version: HidingBar-v10.1.3
* WoW version: 10.1.5 (50469) (Release x64)

1) install HidingBar
2) try to hide HidingBar's button, either via "LMB to enable / disable buttons", or the "Ignore List"

HidingBar's button is hidden.

HidingBar's Button is shown.

N/A

#### Screenshots
![Screenshot 2023-07-18 124359](https://github.com/sfmict/HidingBar/assets/8304460/801db4d5-e321-4efa-b945-855ff7e9fcf8)
![Screenshot 2023-07-18 124347](https://github.com/sfmict/HidingBar/assets/8304460/ecff74f5-483f-40d1-befc-e40967a476ec)
![Screenshot 2023-07-18 124209](https://github.com/sfmict/HidingBar/assets/8304460/77082722-f80d-432f-8ecf-1776b4a88e63)

**Comment by sfmict** [comment]
Hello, thx you for feedback, fixed :)

**Comment by durandal42** [comment]
Confirmed fixed as of HidingBar-v10.1.4, thank you!
