### ISSUE TITLE
Bar like a minimap button

### ISSUE THREAD

**Issue by TRAMAduck** [sfmict/HidingBar#25]
#### Environment
* Addon version: 10.1.6
* WoW version: 10.1.5

#### Steps to reproduce
Login

#### Expected Behaviour
Maintain button size

#### Actual Behaviour
Button is probably twice as large.  Button size says 20, but is much bigger.  If I change the button size to something else and immediately back, it goes to the correct size.

#### Screenshots
![WoWScrnShot_090323_092111](https://github.com/sfmict/HidingBar/assets/118639944/9fc4a0d5-ec26-4166-b195-db9563a7400c)
![WoWScrnShot_090323_092120](https://github.com/sfmict/HidingBar/assets/118639944/d3c0cb37-1ae1-4a0b-b921-497144ce6399)

**Comment by sfmict** [comment]
Hello, this is doing by SexyMap, so you can use its settings to change that.
