### ISSUE TITLE
Conflict: Exlist's tooltip does not hide after mouseout.

### ISSUE THREAD

**Issue by class2u** [sfmict/HidingBar#26]
#### Environment
* Addon version: v10.1.11
* WoW version: 10.1.7, zhTW Client

#### Steps to reproduce
1. Install the Exlist addon.
2. Mouseover it's minimap button.
3. Mouseout the minimap button.

#### Expected Behaviour
The Exlist's tooltip hides after mouseout.

#### Actual Behaviour
The Exlist's tooltip is still there and no way to hide it except /reload.

I am not sure it is the issue of Exlist or HidingBar.
But the Exlist's tooltip does hide after mouseout when HidingBar is not loaded.

#### Debug Output
No lua error.

**Comment by sfmict** [comment]
Hello, I can fix this situation a little, the button must be visible for its script to work. Only the author of the addon will fix this completely.

**Comment by class2u** [comment]
Thanks for replying so quickly. I logged this issue in Exlist.

**Comment by sfmict** [comment]
As far as I understand, this has been fixed.
