### ISSUE TITLE
Add "Dragonflight UI Classic" compatibility

### ISSUE THREAD

**Issue by adam-tj** [sfmict/HidingBar#28]
#### Environment
* Addon version: 1.15.11
* WoW version: 1.15.3 (Season of Discovery)

#### Desired functionality
The addon is not completely compatible with the "Dragonflight UI Classic" addon.
The minimap button mode (Bar like a minimap button) looks very ugly.
The button should either look similar to how it looks like with the default UI or to how it looks like in one of the screenshots displayed on Github and Curseforge.

**Comment by sfmict** [comment]
Addon uses libraries, for minimap button and for button skins, you can install addon masque for that.
You should read a description.
