### ISSUE TITLE
Error HidingBar\Config.lua:898: v9.0.11

### ISSUE THREAD

**Issue by Ecleos** [sfmict/HidingBar#3]
Message: Interface\AddOns\HidingBar\Config.lua:898: attempt to perform arithmetic on field 'secondPosition' (a nil value)
Time: Sun Dec 13 10:07:58 2020
Count: 1
Stack: Interface\AddOns\HidingBar\Config.lua:898: attempt to perform arithmetic on field 'secondPosition' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HidingBar\Config.lua"]:898: in function `updateCoords'
[string "@Interface\AddOns\HidingBar\Config.lua"]:772: in function <Interface\AddOns\HidingBar\Config.lua:44>
[string "=[C]"]: in function `Show'
[string "@Interface\FrameXML\UIParent.lua"]:2910: in function `SetUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2716: in function `ShowUIPanel'
[string "@Interface\FrameXML\UIParent.lua"]:2623: in function <Interface\FrameXML\UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@Interface\FrameXML\UIParent.lua"]:3468: in function <Interface\FrameXML\UIParent.lua:3447>
[string "=[C]"]: ?
[string "=[C]"]: in function `ShowUIPanel'
[string "@Interface\AddOns\Oilvl\Oilvl.lua"]:5912: in function `?'
[string "@Interface\AddOns\Oilvl\Oilvl.lua"]:6059: in function <Interface\AddOns\Oilvl\Oilvl.lua:6058>

Locals: 

Message: Interface\AddOns\HidingBar\Config.lua:898: attempt to perform arithmetic on field 'secondPosition' (a nil value)
Time: Sun Dec 13 10:08:04 2020
Count: 1
Stack: Interface\AddOns\HidingBar\Config.lua:898: attempt to perform arithmetic on field 'secondPosition' (a nil value)
[string "=[C]"]: ?
[string "@Interface\AddOns\HidingBar\Config.lua"]:898: in function `updateCoords'
[string "@Interface\AddOns\HidingBar\HidingBar.lua"]:968: in function `setBarPosition'
[string "@Interface\AddOns\HidingBar\HidingBar.lua"]:466: in function `init'
[string "@Interface\AddOns\HidingBar\HidingBar.lua"]:111: in function <Interface\AddOns\HidingBar\HidingBar.lua:111>

Locals:

**Comment by Road-block** [comment]
```
34x HidingBar\Config.lua:1173: attempt to index field 'buttonPanel' (a nil value)
HidingBar\Config.lua:1173: in function 'applyLayout'
HidingBar\Config.lua:555: in function <HidingBar\Config.lua:549>
[C]:: in function 'SetValue'
HidingBar\Config.lua:551: in function <HidingBar\Config.lua:549>
```
and 
```
2x HidingBar\Config.lua:888: attempt to perform arithmetic on field 'secondPosition' (a nil value)
HidingBar\Config.lua:888: in function 'updateCoords'
HidingBar\Config.lua:762: in function <HidingBar\Config.lua:44>
[C]:: in function 'Show'
FrameXML\InterfaceOptionsFrame.lua:204: in function 'InterfaceOptionsFrame_Show'
FrameXML\InterfaceOptionsFrame.lua:487: in function 'InterfaceOptionsFrame_OpenToCategory'
HidingBar\Config.lua:1186: in function 'openConfig'
HidingBar\Config.lua:1195: in function '?'
FrameXML\ChatFrame.lua:4693: in function <FrameXML\ChatFrame.lua:4639>
[C]:: in function 'ChatEdit_ParseText'
FrameXML\ChatFrame.lua:4356: in function <FrameXML\ChatFrame.lua:4355>
[C]:: in function 'ChatEdit_SendText'
FrameXML\ChatFrame.lua:4392: in function 'ChatEdit_OnEnterPressed'
[string "*:OnEnterPressed"]:1: in function <[string "*:OnEnterPressed"]:1>
```

**v1.13.27** Classic

When changing something in the config or doing a mouseover show.

**Comment by sfmict** [comment]
Thx yours. Fixed, pls check.

**Comment by Ecleos** [comment]
Thx, very good job
