### ISSUE TITLE
Cata Firelands PTR - Bug Report

### ISSUE THREAD

**Issue by Raina1007** [sfmict/HidingBar#31]
#### Environment
* Addon version: 4.4.1
* WoW version: Cata PTR

I went on the Cata PTR and been on it off and on for weeks, then they took the servers down last Wednesday and brought back up on Thursday of last week. Unfortunately they made some change to things and now Hiding Bar is having Lua Errors. I wasn't able to copy the lua error even with BugSack/BugGrabber as they have disabled shortcut keys for MacOS, but I did get screenshots. Hiding Bar is working, but there is a ton of Lua Errors that I can't close out. Not sure what they changed and if anything needs to be done or just gotta wait on Blizz to fix. 

No lua errors

Got Lua Errors - see screenshot

See Screenshots - unable to c/p as shortcuts are disabled on the Cata PTR

<img width="986" alt="Screenshot 2024-09-09 at 10 12 08 AM" src="https://github.com/user-attachments/assets/2c49384a-79e6-424d-a377-1905fdbafc3b">
<img width="937" alt="Screenshot 2024-09-09 at 10 12 24 AM" src="https://github.com/user-attachments/assets/71d6b37d-9989-4dc6-bd52-1796e2c8c3c2">
<img width="942" alt="Screenshot 2024-09-09 at 10 12 37 AM" src="https://github.com/user-attachments/assets/743a2087-447d-49b0-ba06-d152a5e05179">
<img width="942" alt="Screenshot 2024-09-09 at 10 12 55 AM" src="https://github.com/user-attachments/assets/90a5e44f-b0c1-4678-b296-a711545bd2af">

**Comment by sfmict** [comment]
Hi, fixed :)
