### ISSUE TITLE
2 feature suggestions

### ISSUE THREAD

**Issue by zeenk** [sfmict/HidingBar#32]
Hi,

I have some suggestion/ideas for this addon that I think could be nice to have 🙂 
1. Option to fade/only show the HidingBar button while hovering the minimap
Like this (feature from this addon) [BasicMinimap](https://www.curseforge.com/wow/addons/basic-minimap)

https://github.com/user-attachments/assets/207cf280-3f7b-413d-98ff-79c8b1a25a92

2. Right click the minimap button to open addon settings for this addon

**Comment by sfmict** [comment]
Hi,
1. I'll think about it, this option may conflict with some addons like BasicMinimap.
2. You can open the setting with right-click+shift

**Comment by zeenk** [comment]
> 2. You can open the setting with right-click+shift

Oh, didn't know about that 👍

**Comment by sfmict** [comment]
Added, check :)

**Comment by zeenk** [comment]
Perfect, thank you 🙂
