### ISSUE TITLE
Feature Request: Bar Alignment

### ISSUE THREAD

**Issue by addonaddict** [sfmict/HidingBar#4]
90002 
* Addon version: v1.13.31
* WoW version: latest as of 28th dec.. idk..

Would love to see an option to anchor the bar to the middle of your screen (or more anchor points if possible)
I tend to put my bar at top of my screen in the middle with 1 row of buttons
I constantly have to re-adjust it when adding more addons or changing UI scale
Best case scenario would be to allow bar to anchor it's top center point with UI top center point so that if more buttons are added, the bar stretches out equally both ways

I understand this may be confusing to code with so many ways to have your bars

Thanks :)

![image](https://user-images.githubusercontent.com/73442541/103204300-0683f300-48c5-11eb-98e5-93bbfeeb0e49.png)

**Comment by sfmict** [comment]
I can do to panel expand in both directions. I think it will do what you want. But don't sure what i will do it in this year. :)

**Comment by sfmict** [comment]
Check beta version pls :).

**Comment by addonaddict** [comment]
Done, opened another issue
Thanks :D

**Comment by addonaddict** [comment]
Ive tried the beta version and it works good (expand to both direction)
I wouldnt mind to be able to snap the bar to center of screen horizontally, but if its more complicated than that then its ok, this is more than enough :)

thank you

**Comment by sfmict** [comment]
thx for feedback 👍🏻
