### ISSUE TITLE
Beta build outputs errors  v1.13.32-beta1

### ISSUE THREAD

**Issue by addonaddict** [sfmict/HidingBar#5]
90002 Environment
* Addon version: v1.13.32-beta1
* WoW version: idk latest 28th dec

Login
minimap button gets absorbed, different from before
minimap icons are unclickable, databroker are OK

20x [string "<unnamed>:OnLoad"]:1: attempt to call method 'SetBackdrop' (a nil value)
[string "*:OnLoad"]:1: in function <[string "*:OnLoad"]:1>
[string "=[C]"]: in function `CreateFrame'
[string "@HidingBar\Config.lua"]:57: in function `createTabPanel'
[string "@HidingBar\Config.lua"]:123: in function <HidingBar\Config.lua:44>
[string "=[C]"]: in function `Show'
[string "@FrameXML\UIParent.lua"]:2910: in function `SetUIPanel'
[string "@FrameXML\UIParent.lua"]:2716: in function `ShowUIPanel'
[string "@FrameXML\UIParent.lua"]:2623: in function <FrameXML\UIParent.lua:2619>
[string "=[C]"]: in function `SetAttribute'
[string "@FrameXML\UIParent.lua"]:3468: in function `ShowUIPanel'
[string "@Oilvl\Oilvl-v8.3 BFA.lua"]:5912: in function `?'
[string "@Oilvl\Oilvl-v8.3 BFA.lua"]:6059: in function <Oilvl\Oilvl.lua:6058>

Locals:
self = <unnamed> {
 0 = <userdata>
}
(*temporary) = nil
(*temporary) = <unnamed> {
 0 = <userdata>
}
(*temporary) = <table> {
 bgFile = "Interface/Tooltips/UI-Tooltip-Background"
 tileSize = 14
 edgeFile = "Interface/Tooltips/UI-Tooltip-Border"
 tile = true
 edgeSize = 14
 tileEdge = true
 insets = <table> {
 }
}
(*temporary) = "attempt to call method 'SetBackdrop' (a nil value)"

![image](https://user-images.githubusercontent.com/73442541/103235758-d9f5c880-4910-11eb-95cf-87addc4ed21b.png)

**Comment by sfmict** [comment]
You use classic version for retail :)))

**Comment by addonaddict** [comment]
q_q my bad
