### ISSUE TITLE
[Feature Request] Button masking, snap-anchoring, 

### ISSUE THREAD

**Issue by addonaddict** [sfmict/HidingBar#6]
* Addon version: v9.0.17
* WoW version: 90002
* Retail

This is just  a suggestion from a long-time user, feel free to close this if you don't find it necessary, I understand!
1. I would love an option to skin the buttons within HidingBar options UI. I am aware of Masque, but I tend to stay away from addons that require installing other addons. I like to keep it simple, same as a lot of other users i'm sure
Currrently, minimap buttons and databroker buttons are skinned differently by default (for obvious reasons)
Any chance we could add an option to skin blizz minimap buttons to match the data broker? This way all buttons look the same
![image](https://user-images.githubusercontent.com/73442541/103956910-81e07280-5117-11eb-8996-f14168c71db1.png)

2. This isn't too important. Can we get some kind of bar snap-anchoring? When dragging the bar, mouse cursor is set to the intended anchor location deppending how the user has his bar layout. In my case for example, I have a bar at top of screen with buttons running in "both directions". So my bar snaps to vertical center of screen at top.
Is it possible to have the bar "snap" to that vertical axis when the mouse is close enough? Similar to "Dominos" action bar addon functionality. 
It would be X and Y center points of screen (not sure if other users may want different snap points?)

3. Tooltip positions when mousing over buttons is all set by addons, which means all are different. Could the addon have an option to where the tooltip will open up? i.e. top right, top left, bottom right, top, bottom, etc. Possible even add cursor offset X and Y similar to tooltip addons. This option would override all other settings set by other addons/blizz UI.
Examples of differences currently:
![image](https://user-images.githubusercontent.com/73442541/103957261-50b47200-5118-11eb-9aaf-fe47e95c46ca.png)
![image](https://user-images.githubusercontent.com/73442541/103957282-5e69f780-5118-11eb-844f-3599ff3c1545.png)
![image](https://user-images.githubusercontent.com/73442541/103957295-6a55b980-5118-11eb-92da-bde41b1d213c.png)
As yuou can see, all are positioned differently. AlltheThings is right in the middle of the icon, blocking view of others, rest are center bottom or left bottom. Im sure some other addons are different, I remember some (maybe SavedInstances) was blocking absolutely everything so you had to un-hover to minimize the hidingbar and then hover again on different icon. Was SUPER annoying so I got rid of that addon.

Just some ideas to make it perfect, thank you so much for this wonderful addon, it is miles ahead of MBB :)

**Comment by sfmict** [comment]
Hi thx for feedback 👍🏻 

1. The Masque gives a huge choice, and I don't see any sense in adding my own. 
2. I will add a point in the center.
3. I only manage the anchor point of tooltips from the DataBroker. Intercepting tooltips from minimap buttons can create many unnecessary problems.
