### ISSUE TITLE
HidingBar configuration screen not populated

### ISSUE THREAD

**Issue by Torqueitup** [sfmict/HidingBar#7]
Win10 Home
#### Environment
* Addon version: 1.13.53
* WoW version: Classic 1.14.0.40347

Disable ALL addons.  Enable HidingBar, Arkinventory, Bartender, Icehud

From the command line typing /hidingbar should bring up a populated configuration screen
Shift or CTRL mouse right click should have actioned something

The configuration screen appears but it is blank.  A single screen with no tabs to include separate config information
Shift or CTRL mouse right click should have actioned something - but nothing happened at all.

No errors were produced

![image](https://user-images.githubusercontent.com/91725389/135592893-8e2e0e48-2c1f-47e0-9d31-2ee58d147763.png)
![image](https://user-images.githubusercontent.com/91725389/135593166-32874021-a738-419c-8da3-18ab35801cca.png)

**Comment by sfmict** [comment]
Classic wow is now 1.14. Will update soon :).

**Comment by sfmict** [comment]
Fixed, thx for feedback.

**Comment by Torqueitup** [comment]
Yup, brilliant - all fixed.  Thanks for the quick turnaround.  Incidentally there are alot of other addons that are suffering from the same update.
